### ISSUE TITLE
Brackets Includes Tags

### ISSUE THREAD

**Issue by jERCle** [pranaygp/vscode-css-peek#10]
Brackets gives you the option to peek definitions for tags as well as the classes.

Is this possible for this extension?

**Comment by pranaygp** [comment]
Currently, this only works for class names and ids. It would be awesome to mimic the functionality of brackets better to make it also do tags, though I never got around to it :/

Would definitely be useful to have

**Comment by jERCle** [comment]
I'm pretty new, but will see if I can figure it out. Bare in mind it would be my first ever pull request if I manage to figure it out though haha.

I'll have a play with it today. I love this extension, the only thing I'm missing from Brackets is that part of the peek. Cheers for letting me know it's not currently a feature! :)

**Comment by pranaygp** [comment]
An update:

I am in the middle of a rewrite of the codebase for this extension (making use of the new [Language Server Protocol](https://github.com/Microsoft/language-server-protocol)).

When releasing the new version (2.0) after this rewrite, I'll also make sure it supports normal HTML tag selectors (but won't support [fancier things](https://www.w3.org/TR/selectors/#attribute-selectors) like `[data-key="value"]` ).

**Comment by pranaygp** [comment]
Version 2.0 is out now and I added support for HTML tags. Brackets allows you to find a definition from both, the opening and closing HTML tags, but I'm limiting this to only the opening tags since that just seems to make more sense.

I'm happy to extend it to allow triggering the definition lookup from the closing tag too if people want that
