### ISSUE TITLE
CPU 95% (12 threading)

### ISSUE THREAD

**Issue by mitivil** [pranaygp/vscode-css-peek#134]
**VS.code css-peek-4.2.0**
, it still heavily overloads the processor and memory.
This process (VS.code css-peak-4.2.0) does not terminate in the usual way of closing the application, you have to kill manually and it hangs in the background :(
Loads almost all 6 processor cores, 12 threads.
Even after the completion of VS.code, it was necessary to kill the process (VS.code css-peek-4.2.0) because he worked on a permanent basis))).
I had to delete it.

My Linux and Windows environment

:))) mining ?

**Comment by pranaygp** [comment]
@mitivil thanks for bringing this up. There are number of issues like this about CPU usage that I've been trying to look into. I'll keep you posted when I hear more - in the meantime, and help with a pull request to fix the issue will help too since I might be a bit slow on this

(no mining. just not very good coding)

**Comment by pranaygp** [comment]
@mitivil can you please provide any information on what workspace you opened when using CSS Peek? Specifically I'm curious how many .css, .less, and .sass files are in the workspace (excluding `node_modules`),

**Comment by pranaygp** [comment]
This has been fixed in version v4.3.4
