### ISSUE TITLE
Peek and Go to Definition both shows / duplicate

### ISSUE THREAD

**Issue by thwyster** [pranaygp/vscode-css-peek#48]
Hi,

When I press F12 (Go To: jump directly to the css file or open it in a new editor), the Css Peek Go to File and show a Peek in Css File, it's confusing!

![image](https://user-images.githubusercontent.com/3345073/48284473-a90f5c80-e446-11e8-8d36-61c7ff650cda.png)

In F12 must be go to css file, not show a peek.
Peek just only show using Ctrl+Shift+12 but if I use Ctrl+Shift+F12 in sass class, not show peek

![image](https://user-images.githubusercontent.com/3345073/48284788-a3fedd00-e447-11e8-889f-f69dd98abbac.png)

What's Happens??

**Comment by pranaygp** [comment]
This doesn't look like an issue with CSS Peek

If there are multiple definitions available for a css element, like in the screenshot above, then VSCode will always show the peek window instead of jumping.

In the first screenshot, that's not using CSS Peek. Peeking a css class inside a .css file happens directly using the CSS support built into VSCode. it's not handled by CSS Peek.

If CSS Peek is not working in the second example, when it should, please update to latest CSS Peek and try again. If it's still an issue, please open a new issue here with and example repo/codebase I can use to test and reproduce the issue
