### ISSUE TITLE
The extension is messed up my PC

### ISSUE THREAD

**Issue by uklertis** [pranaygp/vscode-css-peek#57]
Today I installed this extension and VSCode started to freeze randomly. After that I deleted the extension but some how VSCode keep freezing and I BELIEVE SOME HOW THIS EXTENSION STILL CAUSE THAT... so my point is don't use the extension!

**Comment by pranaygp** [comment]
@uklertis happy to help you debug your issue. if VS Code is still crashing all the time after removing CSS Peek, you might still have to reload VS Code for that to take effect. Also make sure you're on the latest version of VS Code :)

**Comment by uklertis** [comment]
I have the latest version already and even if reinstall VS Code still the same. When I opened VS Code after a while(like 1-2 hours later) my pc get slower and slower.

**Comment by acheng33** [comment]
@uklertis it's definitely not caused by CSS Peek then and you should open an issue over on [VS Code](https://github.com/Microsoft/vscode) who might need more logs from you to help debug the issue. You can also confirm that you've gotten rid of all the CSS Peek files by going to the command pallette (<kbd>Cmd</kbd><kbd>Shift</kbd><kbd>P</kbd>), search for "Open Extensions Folder" and search for "pranaygp.vscode-css-peek-2.2.0". If it's still there, delete the folder and restart VS Code
