### ISSUE TITLE
Support for SCSS/Sass

### ISSUE THREAD

**Issue by PixelT** [pranaygp/vscode-css-peek#7]
Do you plan to add support for scss/sass files?

**Comment by pranaygp** [comment]
Yup, that's been the plan for a while now. Before adding SASS support, however, I'd like to move css peek to using a CSS language service instead of searching for and compiling every style file everytime (as it does now).

Once we're using a language service, we can extend the language service to include SASS files

**Comment by pranaygp** [comment]
I am in the middle of a rewrite of the codebase for this extension (making use of the new Language Server Protocol).

When releasing the new version (2.0) after this rewrite, I'll also make sure it supports SASS (or at least in version 2.1)

I'm keeping this issue open till it gets implemented

**Comment by pranaygp** [comment]
It'd been implemented and version 2.0 is out now! 
Try it out in a VSCode installation near you ❤️

**Comment by onetrev** [comment]
Exciting! Thank you for doing this. But I'm having issues. Still no luck with it finding my class definitions in my SCSS files. I have HTML in PHP so I made this change to add PHP support (almost wonder if that should be default since it's so common to have HTML in your PHP), but still no luck.

`
    "css_peek.activeLanguages": [
        "html",
        "php",
        "ejs"
    ],
`
If I change the file language to HTML, it works perfectly though. So something to do with the PHP language type.

**Comment by pranaygp** [comment]
Adding PHP as a default makes sense. I'll test it soon (I think I know what's causing the error) and push a fix soon.

Thanks for reporting that :)

**Comment by pranaygp** [comment]
@onetrev I pushed an update (2.0.2) and also added php to the defaults.

Can you update your version and try again. I hope it works 😃

**Comment by onetrev** [comment]
Works perfectly!! Hot stuff. Highlight of my week, easily. Thanks again!
